import { readFile, readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import pg from 'pg';

const { Client } = pg;

const apiRoot = resolve(__dirname, '../..');
const bundlePath = join(
  apiRoot,
  'db/ops/2026-07-22_apply_equipment_schema_and_data.sql',
);
const sourcePaths = [
  'db/migrations/014_equipment_evidence.sql',
  'db/migrations/015_clear_autogenerated_equipment.sql',
  'db/migrations/016_equipment_models.sql',
  'db/manual-data/001_soundcity_keyboard_equipment.sql',
  'db/manual-data/002_soundcity_backline_equipment.sql',
  'db/manual-data/003_soundcity_position_label_cleanup.sql',
  'db/manual-data/004_hongdae_naver_room_equipment.sql',
  'db/manual-data/005_catalog_room_core_equipment.sql',
] as const;

describe('Render 장비 적용 SQL 번들', () => {
  it('원본 SQL을 빠짐없이 한 번씩 같은 순서로 포함한다', async () => {
    const bundle = await readFile(bundlePath, 'utf8');
    let previousIndex = -1;

    for (const relativePath of sourcePaths) {
      const source = (await readFile(join(apiRoot, relativePath), 'utf8')).trim();
      const sourceIndex = bundle.indexOf(source);

      expect(sourceIndex).toBeGreaterThan(previousIndex);
      expect(bundle.lastIndexOf(source)).toBe(sourceIndex);
      previousIndex = sourceIndex;
    }

    expect(bundle.trimStart().startsWith('-- Render/Postgres one-off apply script')).toBe(
      true,
    );
    expect(bundle).toMatch(/\nBEGIN;\n/);
    expect(bundle.trimEnd().endsWith('COMMIT;')).toBe(true);
  });
});

const runIntegration = process.env.RUN_OPS_DB_TESTS === '1';
const describeIntegration = runIntegration ? describe : describe.skip;

type Summary = {
  equipmentModels: number;
  roomEquipment: number;
  equipmentEvidence: number;
  catalogEvidence: number;
  roomsWithEquipment: number;
  roomsWithoutEquipment: number;
  completeStudios: number;
  partialStudios: number;
  emptyStudios: number;
  catalogStudios: number;
  catalogRooms: number;
  fullyModeledCatalogRooms: number;
  partiallyModeledCatalogRooms: number;
  unknownSourceRooms: number;
  unknownSourceEvidence: number;
  remainingPositionLabels: number;
  remainingOrdinalEvidence: number;
};

describeIntegration('Render 장비 적용 SQL 번들 (Postgres 통합)', () => {
  const adminUrl = process.env.OPS_TEST_DATABASE_URL;
  const databaseName = `hapjusil_ops_test_${process.pid}_${Date.now()}`;
  let adminClient: InstanceType<typeof Client>;
  let testClient: InstanceType<typeof Client>;
  let testUrl: string;
  let firstSummary: Summary;

  jest.setTimeout(120_000);

  beforeAll(async () => {
    if (!adminUrl) {
      throw new Error(
        'RUN_OPS_DB_TESTS=1 실행에는 OPS_TEST_DATABASE_URL이 필요합니다.',
      );
    }

    const parsedUrl = new URL(adminUrl);
    if (!['localhost', '127.0.0.1', '[::1]'].includes(parsedUrl.hostname)) {
      throw new Error('장비 적용 통합 테스트는 로컬 Postgres에서만 실행할 수 있습니다.');
    }

    adminClient = new Client({ connectionString: adminUrl, ssl: false });
    await adminClient.connect();
    await adminClient.query(`CREATE DATABASE ${quoteIdentifier(databaseName)}`);

    parsedUrl.pathname = `/${databaseName}`;
    testUrl = parsedUrl.toString();
    testClient = new Client({ connectionString: testUrl, ssl: false });
    await testClient.connect();

    await applyPrerequisites(testClient);
    await testClient.query(await readFile(bundlePath, 'utf8'));
    firstSummary = await readSummary(testClient);
  });

  afterAll(async () => {
    await testClient?.end();

    if (adminClient) {
      await adminClient.query(
        `SELECT pg_terminate_backend(pid)
         FROM pg_stat_activity
         WHERE datname = $1 AND pid <> pg_backend_pid()`,
        [databaseName],
      );
      await adminClient.query(`DROP DATABASE IF EXISTS ${quoteIdentifier(databaseName)}`);
      await adminClient.end();
    }
  });

  it('기준 장비 데이터와 검수 집계를 생성한다', async () => {
    expect(firstSummary).toEqual({
      equipmentModels: 364,
      roomEquipment: 1242,
      equipmentEvidence: 1254,
      catalogEvidence: 892,
      roomsWithEquipment: 192,
      roomsWithoutEquipment: 147,
      completeStudios: 57,
      partialStudios: 4,
      emptyStudios: 70,
      catalogStudios: 53,
      catalogRooms: 155,
      fullyModeledCatalogRooms: 116,
      partiallyModeledCatalogRooms: 39,
      unknownSourceRooms: 1,
      unknownSourceEvidence: 4,
      remainingPositionLabels: 0,
      remainingOrdinalEvidence: 0,
    });
  });

  it('출처 미확정 항목을 겟밴드 아지트 한 곳으로 제한한다', async () => {
    const result = await testClient.query<{
      studio_name: string;
      unknown_room_count: number;
    }>(
      `SELECT s.name AS studio_name, count(DISTINCT r.id)::int AS unknown_room_count
       FROM equipment_evidence ee
       JOIN rooms r ON r.id = ee.room_id
       JOIN studios s ON s.id = r.studio_id
       WHERE ee.source_kind = 'UNKNOWN'
       GROUP BY s.name`,
    );

    expect(result.rows).toEqual([
      { studio_name: '겟밴드 아지트', unknown_room_count: 1 },
    ]);
  });

  it('다시 실행해도 검수 집계가 바뀌지 않는다', async () => {
    await testClient.query(await readFile(bundlePath, 'utf8'));

    expect(await readSummary(testClient)).toEqual(firstSummary);
  });
});

async function applyPrerequisites(client: InstanceType<typeof Client>) {
  const migrationDirectory = join(apiRoot, 'db/migrations');
  const migrationFiles = (await readdir(migrationDirectory))
    .filter((file) => file.endsWith('.sql') && file < '014_')
    .sort();
  const seedDirectory = join(apiRoot, 'db/seeds');
  const seedFiles = (await readdir(seedDirectory))
    .filter((file) => file.endsWith('.sql'))
    .sort();

  for (const file of migrationFiles) {
    await client.query(await readFile(join(migrationDirectory, file), 'utf8'));
  }
  for (const file of seedFiles) {
    await client.query(await readFile(join(seedDirectory, file), 'utf8'));
  }
}

async function readSummary(client: InstanceType<typeof Client>): Promise<Summary> {
  const result = await client.query<Summary>(`
    WITH room_coverage AS (
      SELECT r.id, r.studio_id, count(re.id)::int AS equipment_count
      FROM rooms r
      LEFT JOIN room_equipment re ON re.room_id = r.id
      GROUP BY r.id, r.studio_id
    ),
    studio_coverage AS (
      SELECT
        studio_id,
        count(*)::int AS room_count,
        count(*) FILTER (WHERE equipment_count > 0)::int AS equipped_room_count
      FROM room_coverage
      GROUP BY studio_id
    ),
    catalog_room_coverage AS (
      SELECT
        ee.room_id,
        bool_and(ee.equipment_model_id IS NOT NULL) AS fully_modeled
      FROM equipment_evidence ee
      WHERE ee.evidence_key LIKE 'catalog-room-core:%'
      GROUP BY ee.room_id
    )
    SELECT
      (SELECT count(*)::int FROM equipment_models) AS "equipmentModels",
      (SELECT count(*)::int FROM room_equipment) AS "roomEquipment",
      (SELECT count(*)::int FROM equipment_evidence) AS "equipmentEvidence",
      (SELECT count(*)::int FROM equipment_evidence
       WHERE evidence_key LIKE 'catalog-room-core:%') AS "catalogEvidence",
      (SELECT count(*)::int FROM room_coverage
       WHERE equipment_count > 0) AS "roomsWithEquipment",
      (SELECT count(*)::int FROM room_coverage
       WHERE equipment_count = 0) AS "roomsWithoutEquipment",
      (SELECT count(*)::int FROM studio_coverage
       WHERE equipped_room_count = room_count) AS "completeStudios",
      (SELECT count(*)::int FROM studio_coverage
       WHERE equipped_room_count > 0 AND equipped_room_count < room_count) AS "partialStudios",
      (SELECT count(*)::int FROM studio_coverage
       WHERE equipped_room_count = 0) AS "emptyStudios",
      (SELECT count(DISTINCT s.id)::int
       FROM equipment_evidence ee
       JOIN rooms r ON r.id = ee.room_id
       JOIN studios s ON s.id = r.studio_id
       WHERE ee.evidence_key LIKE 'catalog-room-core:%') AS "catalogStudios",
      (SELECT count(*)::int FROM catalog_room_coverage) AS "catalogRooms",
      (SELECT count(*)::int FROM catalog_room_coverage
       WHERE fully_modeled) AS "fullyModeledCatalogRooms",
      (SELECT count(*)::int FROM catalog_room_coverage
       WHERE NOT fully_modeled) AS "partiallyModeledCatalogRooms",
      (SELECT count(DISTINCT room_id)::int FROM equipment_evidence
       WHERE source_kind = 'UNKNOWN') AS "unknownSourceRooms",
      (SELECT count(*)::int FROM equipment_evidence
       WHERE source_kind = 'UNKNOWN') AS "unknownSourceEvidence",
      (SELECT count(*)::int FROM room_equipment
       WHERE position_label IS NOT NULL) AS "remainingPositionLabels",
      (SELECT count(*)::int FROM equipment_evidence
       WHERE evidence_key ~ '(keyboard|guitar-amp)-(i|ii|iii)'
          OR raw_text ~ '^(건반\\s*(I|II|III|lll|:)|기타\\s*[엠앰]프\\s*(I|II|III|:))'
      ) AS "remainingOrdinalEvidence"
  `);

  return result.rows[0];
}

function quoteIdentifier(identifier: string) {
  return `"${identifier.replaceAll('"', '""')}"`;
}
